/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package se.jimlar;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int login=0x7f060002;
        public static final int password=0x7f060001;
        public static final int profiletext=0x7f060003;
        public static final int username=0x7f060000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int profile=0x7f030001;
    }
    public static final class string {
        public static final int ACCOUNT_TYPE=0x7f050001;
        public static final int app_name=0x7f050000;
        public static final int authenticating=0x7f050005;
        public static final int login=0x7f050004;
        public static final int password=0x7f050003;
        public static final int username=0x7f050002;
    }
    public static final class xml {
        public static final int account_preferences=0x7f040000;
        public static final int authenticator=0x7f040001;
        public static final int contacts=0x7f040002;
        public static final int sync_contacts=0x7f040003;
    }
}
